formatters:
  enable:
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 100
      tab-len: 2
      shorten-comments: false
      reformat-tags: true
      chain-split-dots: true
linters:
  default: all
  disable:
    - arangolint
    - bidichk
    - bodyclose
    - canonicalheader
    - clickhouselint
    - contextcheck
    - decorder
    - depguard
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - exhaustruct
    - exhaustruct_v5
    - exptostd
    - fatcontext
    - forbidigo
    - funcorder
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype # Revisar uso de sum types en enums (roles de cofres o tipos de ítems)
    - gocyclo
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - gomodguard_v2
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - iotamixing
    - loggercheck
    - mirror
    - misspell
    - nlreturn
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - tparallel
    - unqueryvet
    - usetesting
    - varnamelen
    - wsl
    - wsl_v5
    - zerologlint
  enable:
    - asasalint
    - asciicheck
    - containedctx
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - godoclint
    - godot
    - goprintffuncname
    - govet
    - iface
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noinlineerr
    - nolintlint
    - reassign
    - recvcheck
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
      ignore-underscore-vars: false
      disable-dec-order-check: false
      disable-init-func-first-check: false
      disable-dec-num-check: false
      disable-type-dec-num-check: false
      disable-const-dec-num-check: false
      disable-var-dec-num-check: false
    depguard:
      rules:
        main:
          allow:
            - $gostd
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
          list-mode: lax
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      verbose: false
    ireturn:
      allow:
        - anon
        - error
        - generic
        - empty
        - stdlib
run:
  timeout: 5m
version: "2"
